import { Link } from 'react-router-dom'
import './EnglishSeventh.css'

function Answer({ label, lines = 1 }) { return lines > 1 ? <label className="seventh-answer">{label}<textarea rows={lines} /></label> : <label className="seventh-answer">{label}<input type="text" /></label> }
function Correction({ children }) { return <details className="seventh-correction"><summary>Show correction</summary><p>{children}</p></details> }

function EnglishSeventhMidterm() {
  return <div className="seventh-page"><header className="seventh-heading"><p className="eyebrow">English · 7th form</p><h1>Mid-Term Test 1</h1><p>Compiled set of four test versions · Language /14 · Spelling /6 · Total /20.</p><Link className="seventh-quiz-link" to="/courses/7eme/english/midterm-1/quiz">Open interactive revision quiz /20 →</Link></header>
    <section className="seventh-section"><h2>Test Version 1 · Zarat Prep School</h2><p>School year 2018–2019 · Class 7B · Teacher: __________ · Total: /20</p><h3>I. Language · /14</h3><p><strong>1. Complete with:</strong> hobby · got · always · members · These · have · old · parents.</p><p>Hi! I am Sam. I am thirteen years ___ . I’m from England and I live in London. We are 7 ___ . William and Elizabeth are my ___ . I have ___ a sister and a brother. ___ are my grandparents. I ___ play with my dog.</p><Correction>old · members · parents · got · These · always.</Correction><p><strong>2. Complete the dialogue:</strong> Mike: Hello, what is your name? John: ___ Mike: Nice to meet you. John: ___ Mike: How old are you? John: ___ Mike: How many brothers have you got? John: ___ Mike: I like listening to music. Do you like reading? John: ___</p><Correction>My name is John. · Nice to meet you, too. · I am 12. · I have got two brothers. · Yes, I do.</Correction><h3>II. Spelling · /6</h3><p><strong>1. Time:</strong> Write four times from the listening activity. <strong>2. Numbers:</strong> 12 = twelve, 40 = forty, 15 = fifteen, 8 = eight. <strong>3. Listening:</strong> Samantha is a pupil; her favourite activity is swimming; she enjoys reading and listening to music.</p></section>

    <section className="seventh-section"><h2>Test Version 2 · Sejnen Prep School</h2><p>Miss Sana Frayjia · 14-11-2019 · Class 7B · Duration: one hour · Total: /20</p><h3>I. Language · /14</h3><p><strong>1. Put the verbs in the right tense:</strong> Jane (be) ___ twelve. This (be) ___ her friend Jack. He always (go) ___ early. Jane always (listen) ___ to music but Jack (like) ___ reading. They (play) ___ video games together.</p><Correction>is · is · goes · listens · likes · play.</Correction><p><strong>2. Match functions:</strong> 1 Hi Tom. How are you? · 2 thanks · 3 This is my new friend Paul · 4 My name is Sarah · 5 How old are you? · 6 I like playing football.</p><Correction>1-b Greeting · 2-a Thanking · 3-d Introducing others · 4-e Introducing oneself · 5-g Asking about age · 6-c Expressing likes.</Correction><p><strong>3. Choose:</strong> These are my grandparents. He is a teacher. On Sunday, we do homework and play video games. We watch TV. My sister likes reading. We go cycling. We have breakfast.</p><p><strong>4. Match parts:</strong> I visit my grandparents ___ ; Peter washes his ___ ; Alfred and Sophie have got ___ ; pastimes are reading ___ ; This is Ann, she is ___ ; I usually get ___.</p><Correction>on Sundays · face every morning · four children · and drawing · my cousin · up late.</Correction><p><strong>5. Reorder:</strong> How many pupils are there in your school? What time do you have lunch? How old are you? Mary sometimes goes to school by bus.</p><p><strong>6. Match functions:</strong> Hello everybody = greeting; I’m Mary = introducing oneself; This is my friend Elvis = introducing others; How old are you? = asking about age; I really love dancing = expressing likes; Thanks = thanking.</p></section>

    <section className="seventh-section"><h2>Test Version 3 · Class 7th Form</h2><h3>I. Language · /14</h3><p><strong>1. Circle the correct alternative:</strong> Tina is from Britain. Her name is Paul’s friend? Use: <em>from · Her · has · is · Their · mother · goes · on</em> in the paragraph about Paul and Linda.</p><Correction>from · Her · has · is · Their · mother · goes · on.</Correction><p><strong>2. Match functions:</strong> Hello everybody; I’m Mary; This is my new friend Elvis; How old are you?; What is your favourite pastime?; I really love dancing.</p><Correction>Greeting · Introducing oneself · Introducing others · Asking about age · Asking about likes · Expressing likes.</Correction><p><strong>3. Complete the dialogue:</strong> John: Hello. My name is John. Mike: Nice to meet you. John: ___ Mike: Are you new? John: ___ Mike: How old are you? John: ___ Mike: How many brothers? John: ___ Mike: What is your hobby? John: ___ Mike: Do you like reading? John: ___</p><Correction>Pleased to meet you, too. · No, I’m not. · I am 12. · I’ve got two. · I like listening to music. · Yes, I do.</Correction></section>

    <section className="seventh-section"><h2>Test Version 4 · Class 7th Form</h2><h3>I. Language · /14</h3><p><strong>1. Complete the paragraph:</strong> The artist ___ gets up at ten ___ in the morning. She never gets up ___. She gets home at ___ o’clock and paints until seven in the ___. She sometimes ___ to music and ___ the piano. She usually ___ to bed late.</p><Correction>usually · o’clock · early · five (or the time given by the teacher) · evening · listens · plays · goes.</Correction><p><strong>2. Complete the dialogue:</strong> Mike: Hello, what is your name? John: ___ Mike: Nice to meet you. John: ___ Mike: How old are you? John: ___ Mike: How many brothers? John: ___ Mike: I like listening to music. Do you like reading? John: ___</p><Correction>My name is John. · Nice to meet you, too. · I am 12 years old. · I have got two brothers. · Yes, I do.</Correction><p><strong>3. Reorder:</strong> How many sisters have you got? The children love watching TV. Andrew’s favourite pastime is drawing.</p><p><strong>4. Complete:</strong> Fred gets up ___. He ___ his teeth. He starts classes ___ 8 o’clock. At midday, he eats ___. He watches ___. On Saturday, he ___ plays football. ___ are his friends Mario and Thomas.</p><Correction>early · brushes · at · lunch · TV · always · These.</Correction><h3>II. Spelling · /6</h3><p><strong>1. Listening:</strong> Peter is ___ years old. He has got two ___ and one sister. His favourite ___ are playing volleyball and ___. I ___ reading and listening to ___.</p><p><strong>2. Numbers:</strong> 7 = seven · 2 = two · 3 = three · 1 = one · 15 = fifteen · 11 = eleven.</p></section>

    <section className="seventh-section"><h2>Revision checklist</h2><ul><li>Use <strong>is</strong> with he/she/it and <strong>are</strong> with you/we/they.</li><li>Use <strong>has got</strong> with he/she/it and <strong>have got</strong> with I/you/we/they.</li><li>Put frequency adverbs before the main verb: <em>She always reads.</em></li><li>Use <strong>on</strong> with days and <strong>at</strong> with clock times.</li><li>Check capitals, spelling, numbers and punctuation.</li></ul><Answer label="Write a short introduction about yourself: name, age, family, hobbies and favourite activity." lines={7} /><Correction>Example: My name is Sami. I am thirteen years old. I live in Tunisia with my family. I have got one brother. I like reading and playing football. My favourite pastime is listening to music.</Correction></section>
    <Link className="seventh-quiz-link" to="/courses/7eme/english/midterm-1/quiz">Open interactive revision quiz /20 →</Link>
  </div>
}

export default EnglishSeventhMidterm