import { Link } from 'react-router-dom'
import './EnglishFifth.css'

function Answer({ label, lines = 1 }) { return lines > 1 ? <label className="fifth-answer">{label}<textarea rows={lines} /></label> : <label className="fifth-answer">{label}<input type="text" /></label> }
function Correction({ children }) { return <details className="fifth-correction"><summary>✅ Show correction with Arabic meanings</summary><p>{children}</p></details> }

function EnglishFifthUnits() {
  return (
    <div className="fifth-page">
      <header className="fifth-heading"><p className="eyebrow">English · 5th form · Level A1</p><h1>🌍 Units 2–3: Where I’m from & What I like</h1><p>Countries, nationalities, greetings, likes, food and colours.</p><Link className="fifth-quiz-link" to="/courses/5eme/english/units-2-3/quiz">🎯 Open separate quiz /20 →</Link></header>

      <section className="fifth-section"><h2>🗺️ Unit 2 — I’m from...</h2><p><strong>Where are you from?</strong> = من أين أنت؟ · <strong>I’m from Tunisia.</strong> = أنا من تونس.</p><div className="time-cards"><span>🇹🇳<strong>Tunisia</strong><small>تونس · Tunisian = تونسي</small></span><span>🇫🇷<strong>France</strong><small>فرنسا · French = فرنسي</small></span><span>🇨🇦<strong>Canada</strong><small>كندا · Canadian = كندي</small></span><span>🇩🇿<strong>Algeria</strong><small>الجزائر · Algerian = جزائري</small></span></div><p><strong>Key language:</strong> I am = أنا أكون / أنا · He is = هو · She is = هي · They are = هم · Nice to meet you = سعيد بلقائك.</p><h3>Exercise 1: Choose the correct answer</h3><Answer label="1. ___ are you from? (What / Where / Who) 2. I ___ from Tunisia. (am / is / are) 3. He ___ from France. (am / is / are) 4. They ___ from Italy. (am / is / are) 5. Nice to meet you! (Goodbye / Nice to meet you, too / Thank you)" lines={4} /><Correction>1. Where = أين · 2. am = أكون/أنا · 3. is = يكون/هو · 4. are = يكونون/هم · 5. Nice to meet you, too = وأنا سعيد بلقائك أيضًا.</Correction><h3>Exercise 2: Match</h3><Answer label="1. Where are you from? → ___ 2. Nice to meet you. → ___ 3. Where is he from? → ___ 4. Where is she from? → ___" lines={3} /><Correction>1 → I’m from Tunisia. · 2 → Nice to meet you, too. · 3 → He is from France. · 4 → She is from Algeria.</Correction><h3>Exercise 3: Complete</h3><Answer label="Use: am – is – are – I’m – He’s – She’s. 1. I ___ from Tunisia. 2. He ___ from Italy. 3. She ___ from Algeria. 4. We ___ from Morocco. 5. ___ from France. 6. ___ from Canada." lines={4} /><Correction>1. am · 2. is · 3. is · 4. are · 5. I’m · 6. He’s or She’s, depending on the subject. am = أنا، is = هو/هي، are = نحن/هم.</Correction></section>

      <section className="fifth-section"><h2>🍕 Unit 3 — I like...</h2><p><strong>What do you like?</strong> = ماذا تحب؟ · <strong>I like pizza.</strong> = أحب البيتزا. · <strong>I don’t like carrots.</strong> = لا أحب الجزر.</p><div className="time-cards"><span>🍕<strong>pizza</strong><small>بيتزا</small></span><span>🥕<strong>carrots</strong><small>جزر</small></span><span>🥛<strong>milk</strong><small>حليب</small></span><span>🍎<strong>apples</strong><small>تفاح</small></span></div><p><strong>Key language:</strong> Do you like...? = هل تحب؟ · Yes, I do. = نعم، أحب. · No, I don’t. = لا، لا أحب. · favourite = المفضل · colour = اللون · food = الطعام.</p><h3>Exercise 1: Complete the dialogue</h3><div className="dialogue"><p>Words: like · do · don’t · Yes · No</p><p>Sara: ______ you like pizza?</p><p>Tom: ______, I do. I ______ pizza.</p><p>Sara: Do you like carrots?</p><p>Tom: ______, I ______.</p></div><Correction>Do = هل/يفعل · Yes = نعم · like = يحب · No = لا · don’t = لا أفعل. Full dialogue: Do you like pizza? Yes, I do. I like pizza. Do you like carrots? No, I don’t.</Correction><h3>Exercise 2: Unscramble</h3><Answer label="1. like / I / pizza → 2. you / Do / milk / like? → 3. don’t / I / carrots / like → 4. colour / favourite / My / is / blue → 5. apples / like / I →" lines={3} /><Correction>1. I like pizza. 2. Do you like milk? 3. I don’t like carrots. 4. My favourite colour is blue. 5. I like apples.</Correction><h3>Exercise 3: Read and sort</h3><Answer label="Put these words in “I Like” or “I Don’t Like”: pizza, carrots, milk, apples, cake, bananas, cheese, chocolate." lines={4} /><Correction>Answers depend on the learner’s opinion. Example: I like pizza, milk, apples and bananas. I don’t like carrots, cake, cheese and chocolate. like = يحب · don’t like = لا يحب.</Correction><h3>Exercise 4: Write about yourself</h3><Answer label="1. I like ___. 2. I like ___. 3. I don’t like ___. 4. My favourite colour is ___. 5. My favourite food is ___. 6. Do you like ice cream? ___" lines={6} /><Correction>Example: I like pizza. I like apples. I don’t like carrots. My favourite colour is blue. My favourite food is pasta. Yes, I do. favourite = المفضل · ice cream = مثلجات.</Correction></section>

      <section className="fifth-section arabic-box"><h2>📚 Key words — English / Arabic</h2><div className="arabic-grid">{[['where','أين'],['from','من'],['country','بلد'],['nationality','جنسية'],['like','يحب'],['don’t like','لا يحب'],['food','طعام'],['colour','لون'],['favourite','مفضل'],['yes','نعم'],['no','لا'],['meet','يلتقي']].map(([english, arabic]) => <span key={english}><strong>{english}</strong><small>{arabic}</small></span>)}</div></section>
      <Link className="fifth-quiz-link" to="/courses/5eme/english/units-2-3/quiz">🎯 Open separate quiz /20 →</Link>
    </div>
  )
}

export default EnglishFifthUnits
