import { Link } from 'react-router-dom'
import './EnglishSeventh.css'

function Answer({ label, lines = 1 }) { return lines > 1 ? <label className="seventh-answer">{label}<textarea rows={lines} /></label> : <label className="seventh-answer">{label}<input type="text" /></label> }
function Correction({ children }) { return <details className="seventh-correction"><summary>Show correction</summary><p>{children}</p></details> }

function EnglishSeventhUnitTwo() {
  return <div className="seventh-page">
    <header className="seventh-heading"><p className="eyebrow">English · 7th form</p><h1>Unit 2 — Communication and Travel</h1><p>Language functions · Friendly letters · Present progressive · Airport vocabulary.</p><Link className="seventh-quiz-link" to="/courses/7eme/english/unit-2/quiz">Open separate quiz /20 →</Link></header>

    <section className="seventh-section"><h2>1. Lesson objectives</h2><p>By the end of this lesson, you will be able to greet, thank, describe and invite someone; write a friendly letter to a penfriend; use the present progressive in affirmative, negative and interrogative sentences; and use airport and travel vocabulary in a short dialogue.</p><h3>Language functions</h3><div className="seventh-table"><span><strong>Greeting</strong><br />Hi! / Hello! / How are you?</span><span><strong>Thanking</strong><br />Thank you very much. / You’re welcome.</span><span><strong>Describing</strong><br />It is quiet and lovely. / He is kind.</span><span><strong>Inviting</strong><br />Would you like to come to...?</span><span><strong>Taking leave</strong><br />Goodbye. / See you soon.</span></div></section>

    <section className="seventh-section"><h2>2. Writing a friendly letter</h2><p>A friendly letter has a place and date, a salutation, an opening line, an introduction, a body, an invitation or question, and a closing.</p><div className="seventh-reading"><p><strong>Tunis, 3rd September 2026</strong></p><p>Dear Sami,</p><p>Hello! I hope this letter finds you well. My name is Aly and I am very happy to write to you. I am 12 years old and I live in Jerba with my family. I have got one brother and two sisters. My father is a teacher and my mother is a housewife.</p><p>In my free time, I enjoy swimming, reading books and surfing the net. I go to a public school and my favourite subjects are English and Science.</p><p>I am pleased to invite you to visit Jerba next summer. It is quiet and lovely, and I am sure you will enjoy your stay. Please write soon and tell me about your town and your hobbies.</p><p>Yours,<br />Aly</p></div><h3>Exercise 2 – Complete the letter</h3><p>Use: <strong>Dear · Best wishes · hobbies · happy · family</strong>.</p><Answer label="___ Lisa, I am very ___ to write to you. I live in Tunisia with my ___. My favourite ___ are reading and football. ___, Adam." lines={3} /><Correction>Dear · happy · family · hobbies · Best wishes.</Correction><h3>Exercise 12 – Questions to a penfriend</h3><Answer label="Write five questions about family, hobbies and daily routine." lines={5} /><Correction>Examples: What are your hobbies? Where do you live? How many brothers have you got? Do you like swimming? Are you playing sport this weekend?</Correction><h3>Exercise 15 – Vocabulary matching</h3><p>Match: 1 penfriend · 2 salutation · 3 closing · 4 hobby · 5 invite with a the last part of a letter, b a person you write to, c an activity in free time, d ask someone to come, e the greeting at the start.</p><Correction>1-b · 2-e · 3-a · 4-c · 5-d.</Correction></section>

    <section className="seventh-section"><h2>3. Grammar focus: the present progressive</h2><p>We use the present progressive for an action happening now or at the moment of speaking. <strong>Subject + am / is / are + verb-ing.</strong></p><div className="seventh-table"><span><strong>Affirmative</strong><br />I am playing. He is reading. They are watching.</span><span><strong>Negative</strong><br />I am not sleeping. He isn’t working. They aren’t playing.</span><span><strong>Questions</strong><br />Is she dancing? Are they cycling?</span><span><strong>Short answers</strong><br />Yes, she is. No, they aren’t.</span></div><p><strong>Spelling:</strong> play → playing; write → writing; swim → swimming; tie → tying. Signal words: <em>now, at the moment, Look!, Listen!</em></p><h3>Exercise 3 – Put the verbs in the present progressive</h3><Answer label="1. My mother ___ (cook) lunch. 2. The children ___ (play) in the garden. 3. I ___ (not / watch) TV. 4. ___ your brother ___ (do) his homework? 5. We ___ (swim) in the sea." lines={3} /><Correction>1 is cooking · 2 are playing · 3 am not watching · 4 Is / doing · 5 are swimming.</Correction><h3>Exercise 4 – Make questions and answer</h3><Answer label="they / play football · she / write a letter · you / listen to music · the baby / sleep" lines={4} /><Correction>Are they playing football? Yes, they are. Is she writing a letter? Yes, she is. Are you listening to music? Yes, I am. Is the baby sleeping? Yes, it is.</Correction><h3>Exercise 9 – Correct the mistakes</h3><Answer label="1. She are watching TV. 2. I is reading a book. 3. They plays football. 4. He no is doing his homework." lines={4} /><Correction>1. She is watching TV now. 2. I am reading a book at the moment. 3. They are playing football now. 4. He is not doing his homework.</Correction><h3>Exercise 14 – Transform the sentences</h3><Answer label="1. Aly is reading a letter. (negative) 2. They are going to the beach. (question) 3. She is not writing. (affirmative) 4. Peter is staying with Aly. (question + yes answer)" lines={4} /><Correction>1. Aly isn’t reading a letter. 2. Are they going to the beach? 3. She is writing. 4. Is Peter staying with Aly? Yes, he is.</Correction></section>

    <section className="seventh-section"><h2>4. Vocabulary and dialogue: at the airport</h2><div className="seventh-table"><span><strong>passport</strong><br />an official travel document</span><span><strong>luggage</strong><br />bags and suitcases</span><span><strong>trolley</strong><br />a small cart for luggage</span><span><strong>Customs officer</strong><br />checks travellers and luggage</span></div><div className="seventh-reading"><p><strong>Customs Officer:</strong> Good afternoon.<br /><strong>Peter:</strong> Good afternoon, Sir.<br /><strong>Customs Officer:</strong> Can I see your passport, please?<br /><strong>Peter:</strong> Yes, of course. Here you are, Sir.<br /><strong>Customs Officer:</strong> Is this all your luggage?<br /><strong>Peter:</strong> Yes, Sir.<br /><strong>Customs Officer:</strong> Where are you staying?<br /><strong>Peter:</strong> I am staying with my Tunisian friend and his family.<br /><strong>Customs Officer:</strong> Have a nice stay.<br /><strong>Peter:</strong> Thank you. Goodbye.</p></div><h3>Exercise 1 – Match the function</h3><p>1 Greeting · 2 Thanking · 3 Describing · 4 Inviting · 5 Taking leave. Utterances: a You’re welcome. b Hi! How are you? c I am pleased to invite you. d It is quiet and lovely. e Goodbye, see you soon.</p><Correction>1-b · 2-a · 3-d · 4-c · 5-e.</Correction><h3>Exercise 5 – Airport vocabulary</h3><Answer label="1. Peter is showing the Customs officer his ___. 2. His ___ is on a ___." /><Correction>passport · luggage · trolley.</Correction><h3>Exercise 6 – Complete the dialogue</h3><Answer label="Customs Officer: Good morning. Peter: ___. Customs Officer: Can I see your passport? Peter: ___. Customs Officer: Where are you staying? Peter: ___." lines={3} /><Correction>Good morning, Sir. / Yes, of course. Here you are, Sir. / I am staying with my Tunisian friend and his family.</Correction><h3>Exercise 8 – True or False</h3><Answer label="a. Peter shows the officer his trolley. b. Peter is staying with his friend’s family. c. The officer checks his passport twice. d. Peter says Thank you before leaving." /><Correction>a False: he shows his passport. b True. c False: the dialogue mentions it once. d True.</Correction><h3>Exercise 10 – Complete the table</h3><Answer label="Greeting: ___. Polite request: Can I see your passport, please? Thanking: ___. Taking leave: ___." /><Correction>Good afternoon. / Thank you. / Goodbye.</Correction></section>

    <section className="seventh-section"><h2>5. Sounds, grammar and revision</h2><h3>Exercise 11 – Odd one out</h3><p>a. play – day – said – way<br />b. read – bread – head – dead<br />c. house – mouse – route – blouse</p><Correction>a said · b read · c route.</Correction><h3>Exercise 16 – Complete with am / is / are</h3><Answer label="1. I ___ happy to write. 2. My brother ___ nine. 3. We ___ good friends. 4. She ___ a teacher. 5. They ___ from Britain." /><Correction>am · is · are · is · are.</Correction><h3>Exercise 7 – Family activity writing</h3><p>Write 5–6 sentences about what your family is doing on Sunday afternoon.</p><Answer label="It is Sunday afternoon. My family is at home. My father is..." lines={6} /><Correction>Example: My father is reading the newspaper. My mother is cooking lunch. My brother is playing a video game. My sister is drawing. I am listening to music.</Correction></section>

    <section className="seventh-section"><h2>6. Reading comprehension</h2><div className="seventh-reading"><p>It is Saturday afternoon in Jerba. Peter, Aly’s English penfriend, is spending his summer holiday with Aly’s family. Aly’s father is washing his car, and his mother is cooking a tasty couscous for dinner. In the garden, Aly and Peter are looking at old photos and laughing together. Aly’s two little sisters are playing with their dog, and his brother is listening to music. Later, the family is going to the beach to swim and watch the sunset. Peter is really enjoying his stay in Tunisia. He finds Tunisian people friendly and welcoming, and he is already planning to invite Aly to Britain next summer.</p></div><h3>Exercise 13 – Questions</h3><Answer label="1. Who is spending his holiday in Jerba? 2. Where is Peter staying? 3. What is Aly’s mother cooking? 4. Where is the family going later?" lines={4} /><Correction>1. Peter is spending his holiday in Jerba. 2. He is staying with Aly’s family. 3. She is cooking couscous. 4. They are going to the beach.</Correction><h3>True or False</h3><Answer label="a. Peter is staying with Aly’s family. b. Aly’s father is cooking couscous. c. The children are going to the mountains. d. Peter wants to invite Aly to Britain." lines={3} /><Correction>a True · b False: Aly’s mother is cooking couscous · c False: they are going to the beach · d True.</Correction><p><strong>Synonyms:</strong> delicious → tasty · kind and friendly → welcoming · having a good time → enjoying his stay.</p><p><strong>Present progressive verbs:</strong> is spending, is washing, is cooking, are looking, are laughing, are playing, is listening, is going, is enjoying, is planning.</p></section>

    <section className="seventh-section"><h2>7. Extra reading and writing</h2><h3>Bob Johnson — Penfriend paragraph</h3><p>Bob is twelve and enjoys swimming, reading and surfing the net. His father Dave is a teacher, his mother Mary is a housewife, and his younger brother Tom loves music and sport. His sisters Sally and Pamela enjoy dancing and drawing. On Sundays, Bob usually goes cycling, meets friends and eats out.</p><h3>Introducing my best friend</h3><p>Write a letter describing a friend’s appearance, personality, hobbies, likes and dislikes. Use linkers such as <em>also, but, when it comes to, what I admire most</em>.</p><Answer label="My letter to a penfriend" lines={10} /><Correction>Include a date, Dear + name, an introduction, a description, hobbies, likes and dislikes, an invitation or question, and a closing such as “Warm wishes”.</Correction><h3>Daily routine</h3><p>Write a paragraph about Janet’s routine or Peter’s day. Use <em>First, Then, After that, Usually, Finally</em> and the simple present.</p><Answer label="My routine paragraph" lines={7} /><Correction>Example: First, Janet gets up early. Then, she drives to school at 7:30. After that, she starts work at 8:00. Usually, she has lunch at 12:45. Finally, she finishes work at 5:00 and returns home.</Correction></section>
    <Link className="seventh-quiz-link" to="/courses/7eme/english/unit-2/quiz">Open separate quiz /20 →</Link>
  </div>
}

export default EnglishSeventhUnitTwo