import { Link } from 'react-router-dom'
import './EnglishReading.css'

function Answer({ label, lines = 1 }) { return lines > 1 ? <label className="reading-answer">{label}<textarea rows={lines} /></label> : <label className="reading-answer">{label}<input type="text" /></label> }
function Correction({ children }) { return <details className="reading-correction"><summary>Show correction</summary><p>{children}</p></details> }

function EnglishSixthReview() {
  return <div className="reading-page">
    <header className="reading-heading"><p className="eyebrow">English · 6th form</p><h1>English Worksheet · Revision</h1><p>Simple present · Adverbs of frequency · Grammar · Reading comprehension</p><Link className="button-link" to="/courses/6eme/english/revision/quiz">Open the quiz /20 →</Link></header>

    <section className="reading-section"><h2>Grammar practice</h2><h3>Exercise 1 – Fill in the blanks</h3><p>Complete with: <strong>but · usually · playing · is · free · on · because · don’t</strong>. There are two extra words.</p><p>Hello! My name is Tom. My name ___ Tom and I’m eleven years old. I’m good at all subjects ___ English is my favourite one. In my ___ time, I really like playing computer games and watching TV. I ___ watch funny films. I also enjoy ___ football with my friends. I hate reading books ___ it’s boring. Sam always goes to the cinema ___ Sunday evenings.</p><Correction>1 is · 2 but · 3 free · 4 usually · 5 playing · 6 because · 7 on. The extra words are don’t and one unused option depending on the sentence list.</Correction><h3>Exercise 3 – Put the words in the right form</h3><p>Hi! I’m Laura. I (to be) ___ twelve. These are my (friend) ___ Jack and Bob. We always (to go) ___ to school early. I always (read) ___ books.</p><Answer label="Answers" /><Correction>am · friends · go · read.</Correction><h3>Exercise 5 – Put the verbs in the right form</h3><Answer label="a. John usually (to go) ___ to school by bus. b. I enjoy (to fish) ___. c. She sometimes (to play) ___ football. d. It never (rain) ___ in summer. e. My brother always (do) ___ his homework. f. Carla (not / like) ___ drawing." lines={3} /><Correction>goes · fishing · plays · rains · does · doesn’t like.</Correction></section>

    <section className="reading-section"><h2>Simple present and sentence building</h2><h3>Exercise 6 – Choose the correct option</h3><p>a. Our teacher (is / are) helpful. b. We (drinks / drink) coffee. c. She likes (read / reading) books. d. My father (works / work) in a bank. e. (Do / Does) Jimmy and Ben watch TV?</p><Correction>is · drink · reading · works · Do.</Correction><h3>Exercise 7 – Adverbs of frequency</h3><p>Put the words in the correct order.</p><Answer label="a. I (go / usually) ___ to school by bus. b. James (have / sometimes) ___ lunch in a fast food restaurant. c. Vegetarians (eat / never) ___ meat. d. Laura and Lena (play / always) ___ tennis. e. They (visit / often) ___ us." lines={3} /><Correction>I usually go · James sometimes has · Vegetarians never eat · Laura and Lena always play · They often visit.</Correction><h3>Exercise 8 – Reorder the words</h3><p>A. sport / What’s / your / favourite / ?<br />B. usually / is / hungry / Sam / after school.<br />C. about / How / fishing / ?<br />D. enjoy / football / and / They / playing / cycling.</p><Correction>A. What’s your favourite sport? B. Sam is usually hungry after school. C. How about fishing? D. They enjoy playing football and cycling.</Correction><h3>Exercise 9 – Correct the sentence</h3><Answer label="Lucy and Mary dislike practise sport." /><Correction>Lucy and Mary dislike practising sport. / Lucy and Mary dislike practising sports.</Correction></section>

    <section className="reading-section"><h2>Frequency, auxiliaries and possessives</h2><h3>Exercise 10 – Adverbs of frequency</h3><Answer label="A. I ___ (100%) brush my teeth. B. They ___ (50%) go jogging. C. James is ___ (0%) late. D. My grandfather ___ (80%) forgets his birthday." /><Correction>always · sometimes · never · often.</Correction><h3>Exercise 11 – Do / does / don’t / doesn’t</h3><Answer label="A. Carol ___ stay up late. B. ___ you like films? Yes, I ___. C. ___ Jane and Jack ride bikes? No, they ___. D. ___ Janet help at home? She never ___ the washing-up." lines={3} /><Correction>doesn’t · Do / do · Do / don’t · Does / does.</Correction><h3>Exercise 12 – Possessive adjectives</h3><Answer label="A. What’s ___ nationality? B. They are twins. ___ names are Paul and Pedro. C. We are brothers and this is ___ house. D. What’s ___ job? E. Is this ___ book?" /><Correction>your · their · our · her · your.</Correction><h3>Exercise 13 – Prepositions</h3><Answer label="Complete with in, on or at: in the evening · ___ the weekend · ___ night · ___ the holiday · ___ the morning · ___ weekdays." /><Correction>in the evening · at/on the weekend · at night · in the holiday(s) · in the morning · on weekdays.</Correction></section>

    <section className="reading-section"><h2>Questions, suggestions and connectors</h2><h3>Exercise 14 – Wh-questions</h3><Answer label="A. ___ are you from? B. ___ is your favourite hobby? C. ___ is that man? D. ___ is your birthday? E. ___ brothers have you got? F. ___ is that dress? G. ___ hat do you like? H. ___ are you late?" lines={3} /><Correction>Where · What · Who · When · How many · How much · Which · Why.</Correction><h3>Exercise 15 – Making suggestions</h3><p>Choose: What about / Let’s. It’s cold outside. ___ stay at home. The weather is hot. ___ going to the beach. Mum is preparing lunch. ___ helping her. We are tired. ___ take a rest. It’s snowy. ___ go skiing.</p><Correction>Let’s · How about · What about · Let’s · Let’s.</Correction><h3>Exercise 16 – Correct the word</h3><p>A. I’m always busy ___ the weekend. B. Rex doesn’t like Maths because it’s easy ___. C. Lucy enjoys playing video games. It’s boring ___. D. Mom goes shopping ___ the weekend. E. I never go to school ___ Sunday.</p><Correction>A. at/on · B. difficult (or delete “easy” according to the intended meaning) · C. interesting · D. at/on · E. on.</Correction><h3>Exercise 17 – And / but / because</h3><Answer label="A. I enjoy riding bikes ___ I hate playing video games. B. She never studies English ___ it’s difficult. C. I like chicken ___ cheese. D. Sam is absent ___ he’s sick." /><Correction>but · because · and · because.</Correction></section>

    <section className="reading-section"><h2>Reading text: A Day Out</h2><div className="reading-story"><p>On a sunny Saturday morning, two young cousins, Yassine and Abrar, are sitting in the living room and talking about their plans for a day out. Their parents are in the kitchen, and the smell of fresh bread fills the air.</p><p><strong>Yassine:</strong> What shall we do today, Abrar?<br /><strong>Abrar:</strong> How about going to the zoo?<br /><strong>Yassine:</strong> That’s a great idea!<br /><strong>Abrar:</strong> We could also have a picnic in the park.<br /><strong>Yassine:</strong> Yes! Let’s take some sandwiches, juice and fruit.<br /><strong>Abrar:</strong> Why don’t we invite our friends?<br /><strong>Yassine:</strong> Good thought! I’ll call Amine, and you can call Salma.<br /><strong>Abrar:</strong> Perfect! How about we go by bike?<br /><strong>Yassine:</strong> I think it’s better to go by bus. It’s safer and more fun together.<br /><strong>Abrar:</strong> You’re right. Let’s meet at nine o’clock.</p></div><h3>Exercise 19 – True or False</h3><Answer label="1. They are brother and sister. 2. They are talking about a day out. 3. They want to go to the beach. 4. They will take sandwiches and juice. 5. They will invite their friends. 6. They will meet at eight o’clock." lines={3} /><Correction>1. False · 2. True · 3. False · 4. True · 5. True · 6. False.</Correction><h3>Exercise 20 – Answer the questions</h3><Answer label="1. What are Yassine and Abrar talking about? 2. What suggestions do they make? 3. How are they going to go there?" lines={4} /><Correction>1. They are talking about their plans for a day out. 2. They suggest going to the zoo, having a picnic in the park and inviting their friends. 3. They are going to go by bus because it is safer and more fun together.</Correction></section>

    <section className="reading-section"><h2>Useful words</h2><div className="vocabulary-review"><div><span>free time</span><span>leisure time</span><span>usually</span><span>always</span><span>sometimes</span><span>never</span><span>suggestion</span><span>proposition</span><span>day out</span><span>sortie</span></div></div></section>
    <Link className="button-link" to="/courses/6eme/english/revision/quiz">Open the quiz /20 →</Link>
  </div>
}

export default EnglishSixthReview