import { Link, useParams } from 'react-router-dom'
import './EnglishSeventh.css'

function Answer({ label, lines = 1 }) { return lines > 1 ? <label className="seventh-answer">{label}<textarea rows={lines} /></label> : <label className="seventh-answer">{label}<input type="text" /></label> }
function Correction({ children }) { return <details className="seventh-correction"><summary>Show correction</summary><p>{children}</p></details> }

function EnglishFreeTime() { const { level = '6eme' } = useParams(); const form = level === '7eme' ? '7th form' : '6th form'; return <div className="seventh-page"><header className="seventh-heading"><p className="eyebrow">English · {form}</p><h1>Unit 1 — Entertaining Myself</h1><p>Free-time activities · Adverbs of frequency · Prepositions on / in.</p><Link className="seventh-quiz-link" to={`/courses/${level}/english/free-time/quiz`}>Open separate quiz /20 →</Link></header>
  <section className="seventh-section"><h2>Vocabulary: free-time activities</h2><div className="seventh-table"><span>reading books</span><span>dancing</span><span>drawing</span><span>surfing the net</span><span>swimming</span><span>shopping</span><span>playing chess</span><span>riding a bike</span><span>watching TV</span><span>playing sports</span></div><p><strong>Free time = spare time = leisure time.</strong></p><h3>Let’s speak</h3><p>What do you do in your free time? <strong>I usually play football with my friends.</strong><br />What games do you play? <strong>I sometimes play chess and video games.</strong></p></section>
  <section className="seventh-section"><h2>Grammar: adverbs of frequency</h2><p>Adverbs describe how often we do an activity. They come before the main verb, but after <em>am / is / are</em>.</p><div className="seventh-table"><span><strong>always · 100%</strong><br />I always brush my teeth.</span><span><strong>usually · 80%</strong><br />She usually reads.</span><span><strong>sometimes · 50%</strong><br />We sometimes play games.</span><span><strong>never · 0%</strong><br />He never watches scary films.</span></div><p><strong>Subject + adverb + verb:</strong> I usually go shopping. <strong>On</strong> is used with days: on Monday. <strong>In</strong> is used with parts of the day: in the morning.</p><h3>Exercises 1–3</h3><Answer label="1. Match the activity with the word: ride a bike · read books · play football · draw pictures · listen to music · watch TV. 2. Complete: I like to ___ after school. My sister can ___ well. We ___ in the sea. My father likes to ___ dinner. They ___ chess every Sunday. He likes to ___ before bedtime." lines={4} /><Correction>Possible answers: ride a bike · read books · play football · draw pictures · listen to music · watch TV. Exercise 2: read, dance, swim, cook, play chess, watch TV. Exercise 3: reading · listening to · play · swimming.</Correction></section>
  <section className="seventh-section"><h2>Practice and reading</h2><h3>Exercises 4–5: Tom’s Free Time</h3><div className="seventh-reading"><p>Tom is 10 years old. After school, he likes playing football with his friends. In the evening, he reads comics and listens to music. On Saturday, he rides his bike in the park.</p></div><Answer label="1. How old is Tom? 2. What does he do after school? 3. What does he read? 4. What does he do on Saturday?" lines={4} /><Correction>Tom is 10. He plays football after school. He reads comics. On Saturday, he rides his bike in the park. The True/False answers depend on the statements about the learner: use the information given in each sentence and check whether it matches the text.</Correction><h3>Exercises 6–7: choose and complete</h3><Answer label="1. I brush my teeth every day. I ___ brush my teeth. 2. Tom goes once a month. He ___ goes. 3. My baby brother ___ drinks coffee. 4. We eat pizza on Fridays. We ___ eat pizza on Fridays. 5. Sarah watches TV two or three times a week. She ___ watches TV." lines={3} /><Answer label="Complete with always, usually, sometimes or never: I ___ do homework. My father ___ drinks tea. We ___ go swimming in winter. They ___ play football on Sundays. My sister ___ helps my mother." lines={3} /><Correction>Exercise 6: always · sometimes · never · always · sometimes. Exercise 7: answers may vary if they are logical; examples: usually, always, never, always, sometimes.</Correction></section>
  <section className="seventh-section"><h2>Sentence order and personal writing</h2><h3>Exercise 8 – Unscramble</h3><Answer label="1. always / school / I / walk / to. 2. never / late / is / Tom. 3. sometimes / TV / we / watch. 4. usually / breakfast / she / eats. 5. play / they / always / together." lines={4} /><Correction>I always walk to school. Tom is never late. We sometimes watch TV. She usually eats breakfast. They always play together.</Correction><h3>Exercise 9 – Choose the correct answer</h3><p>1. I ___ eat breakfast before school. 2. Penguins ___ fly. 3. My friends ___ visit me at the weekend. 4. We ___ sleep at night.</p><Correction>Possible answers: always · never · sometimes · always.</Correction><h3>Exercise 10 – Write about yourself</h3><Answer label="I always ___. I usually ___. I sometimes ___. I never ___." lines={4} /><Correction>Example: I always brush my teeth. I usually read books. I sometimes go swimming. I never play scary video games.</Correction></section>
  <section className="seventh-section"><h2>Key words</h2><div className="seventh-table"><span>hobby = هواية</span><span>free time = وقت الفراغ</span><span>shopping = التسوق</span><span>swimming = السباحة</span><span>usually = عادةً</span><span>sometimes = أحياناً</span><span>never = أبداً</span><span>weekend = عطلة نهاية الأسبوع</span></div></section><Link className="seventh-quiz-link" to={`/courses/${level}/english/free-time/quiz`}>Open separate quiz /20 →</Link></div> }

export default EnglishFreeTime