import { Link } from 'react-router-dom'
import './EnglishSeventh.css'

function Answer({ label, lines = 1 }) { return lines > 1 ? <label className="seventh-answer">{label}<textarea rows={lines} /></label> : <label className="seventh-answer">{label}<input type="text" /></label> }
function Correction({ children }) { return <details className="seventh-correction"><summary>✅ Show correction</summary><p>{children}</p></details> }

function EnglishSeventhReview() {
  return (
    <div className="seventh-page">
      <header className="seventh-heading"><p className="eyebrow">English · 7th form</p><h1>Module 1 Review</h1><p>Vocabulary · Grammar · Conjugation · Spelling · Writing</p><Link className="seventh-quiz-link" to="/courses/7eme/english/module-1-review/quiz">🎯 Open separate quiz /20 →</Link></header>
      <section className="seventh-section"><h2>👋 1. Introducing others</h2><p>Meriam Tounsi is twelve years old. She is a pupil in Imtiez prep school. Her mother Sana is a doctor. Her father Selim is an English teacher. Her sister Lina is a university student. Her brothers Sami, Ahmed and Yucef are pupils.</p><Answer label="Choose: Meriam is (age / old / young). She is (a / an / the) pupil (in / on / to) school. Sana is her (father / mother / uncle). Selim is an English (teacher / teasher). ___ are pupils." lines={3} /><Correction>twelve years old · a pupil in school · mother · teacher · They are pupils.</Correction></section>
      <section className="seventh-section"><h2>🧑‍🤝‍🧑 2. Subject pronouns</h2><Answer label="Complete: This is Peter. ___ is a pupil. Susan is his sister. ___ is a pupil too. ___ go to the same school. ___ am your new teacher. ___ teach you English. ___ is an easy subject. ___ are pupils. Our school is in Nabeul. ___ isn’t big but ___ is nice." lines={4} /><Correction>He · She · They · I · I · It · We · It · it.</Correction></section>
      <section className="seventh-section"><h2>❓ 3. Questions and answers</h2><p>Match: 1 What’s your name? · 2 How old are you? · 3 Are you a pupil? · 4 Where are you from? · 5 How many brothers? · 6 What are their names?</p><p>Answers: a Yes, I am. · b I’ve got two brothers. · c I’m from Menzel Temime. · d They are Bechir and Ousama. · e I’m Chokri. · f I’m 12.</p><Answer label="Answers: 1 + ___ · 2 + ___ · 3 + ___ · 4 + ___ · 5 + ___ · 6 + ___" /><Correction>1-e · 2-f · 3-a · 4-c · 5-b · 6-d.</Correction></section>
      <section className="seventh-section"><h2>👨‍👩‍👧 4. Have got / Has got</h2><Answer label="Diana is 25. She ___ fair hair and blue eyes. She ___ two brothers but she ___ any sisters. Her brothers ___ brown eyes. Philip is married and ___ two children. The flat ___ five rooms but it ___ a garden. Diana ___ her own room and ___ a computer." lines={4} /><Correction>has got · has got · hasn’t got · have got · has got · has got · hasn’t got · has got · has got.</Correction></section>
      <section className="seventh-section"><h2>⚽ 5. Hobbies and likes</h2><p>Use: favourite · play · enjoy · pastime · listening · video games · cartoons.</p><Answer label="Football is my ___ sport. I usually ___ football. I also ___ watching matches. My favourite ___ is ___ to music. I like playing ___ and watching ___." /><Answer label="Rewrite with -ing: I like video games (play). I enjoy cartoons (watch). I love music (listen)." lines={3} /><Correction>favourite · play · enjoy · pastime · listening · video games · cartoons. I like playing video games. I enjoy watching cartoons. I love listening to music.</Correction></section>
      <section className="seventh-section"><h2>🔀 6. Word order and verb forms</h2><Answer label="Put in order: a) love / very / I / dancing / much. b) is / favourite / My / basketball / pastime. c) your / pastime / tennis / Is / only? d) name / Aly / My / is / classmate’s. e) how many / sisters / and / brothers / have / you / got?" lines={5} /><Answer label="Laura (be) ___. Which sports (do) ___ you like? I like (play) ___. I love (watch) ___. Harry (not like) ___ volleyball and hates (swim) ___." lines={3} /><Correction>I love dancing very much. My favourite pastime is basketball. Is tennis your only pastime? My classmate’s name is Aly. How many brothers and sisters have you got? Laura is · do · playing · watching · doesn’t like · swimming.</Correction></section>
      <section className="seventh-section"><h2>🧠 7. Vocabulary groups</h2><p>Synonyms: favourite = preferred · free time = spare time · pastime = hobby · enjoy = like.</p><Answer label="Put in columns: grandparents, night, headmaster, gardener, cycling, midday, son, daughter, doctor, swimming, afternoon, jogging, mother, teacher, morning." lines={4} /><Correction>Family: grandparents, son, daughter, mother. Hobbies: cycling, swimming, jogging. Jobs: headmaster, gardener, doctor, teacher. Parts of the day: night, midday, afternoon, morning.</Correction></section>
      <section className="seventh-section"><h2>🌅 8. Daily routine</h2><Answer label="Choose: I get up (at / on / in) half past six (at / on / in) the morning. I brush (mine / my / me) teeth. (Then / Before / Later) I have breakfast. I put (on / in / out) my clothes and go to school (by / on / with) foot. I have (breakfast / lunch / dinner) at one. I (wash / watch / wach) TV and go (at / to / in) bed." lines={4} /><Correction>at · in · my · Then · on · on · lunch · watch · to.</Correction></section>
      <section className="seventh-section"><h2>⏰ 9. Simple present and frequency</h2><Answer label="My son often (get) ___ up. He (drink) ___ milk and (eat) ___ biscuits. He (play) ___ with toys. He (watch) ___ television or we (go) ___ for a walk. I (take) ___ him to the park and he (meet) ___ friends." lines={3} /><Answer label="Place the adverb: I have dinner at my friend’s house (sometimes). Caroline eats fish (never). The weather is cold in January (always). I get up late on Sunday (usually)." lines={4} /><Correction>gets · drinks · eats · plays · watches · go · take · meets. I sometimes have dinner. Caroline never eats fish. The weather is always cold. I usually get up late.</Correction></section>
      <section className="seventh-section"><h2>❔ 10. Do, does, is or are</h2><Answer label="1. ___ your father a teacher? 2. ___ your mother work in a bank? 3. When ___ you get up? 4. ___ this your classroom? 5. What ___ your favourite hobby? 6. ___ you good at English?" lines={3} /><Correction>1 Is · 2 Does · 3 do · 4 Is · 5 is · 6 Are.</Correction></section>
      <section className="seventh-section"><h2>📝 11. Articles and negatives</h2><Answer label="Choose a, an or Ø: My mother is ___ doctor. She is ___ beautiful girl. Mary is ___ eleven-year-old pupil. I have ___ egg and ___ sandwich. I read ___ books. She is ___ excellent teacher. They live in ___ old house." lines={3} /><Answer label="Make negative: Maria likes grammar. Clara drives to work. It rains in summer. My parents work in Italy. My brother gets up at seven." lines={5} /><Correction>a · a · an · an · a · Ø · an. Maria doesn’t like grammar. Clara doesn’t drive to work. It doesn’t rain in summer. My parents don’t work in Italy. My brother doesn’t get up at seven.</Correction></section>
      <section className="seventh-section"><h2>✍️ 12. Writing</h2><p>Write five lines about your favourite free-time activities and answer the personal questions about your name, age, country, family and hobbies.</p><Answer label="My paragraph" lines={8} /><Correction>Example: My name is Sami. I am twelve years old. I am from Tunisia. I like playing football and listening to music. I enjoy spending time with my family.</Correction></section>
      <Link className="seventh-quiz-link" to="/courses/7eme/english/module-1-review/quiz">🎯 Open separate quiz /20 →</Link>
    </div>
  )
}

export default EnglishSeventhReview
