import { Link } from 'react-router-dom'
import './FrenchFifth.css'

function Answer({ label, lines = 1 }) { return lines > 1 ? <label className="environment-answer">{label}<textarea rows={lines} /></label> : <label className="environment-answer">{label}<input type="text" /></label> }
function Correction({ children }) { return <details className="environment-correction"><summary>✅ Voir la correction</summary><p>{children}</p></details> }

function FrenchFifthModules() {
  return <div className="environment-page">
    <header className="environment-heading"><p className="eyebrow">Français · 5e année de base</p><h1>Modules 1 &amp; 2</h1><p>Rendons notre environnement plus agréable · Apprenons à vivre ensemble.</p><Link className="environment-quiz-link" to="/courses/5eme/francais/modules-1-2/quiz">🎯 Ouvrir le quiz /20 →</Link></header>

    <section className="environment-section"><h2>Module 1 · Rendons notre environnement plus agréable</h2><h3>Situation 1 : L’embellissement de notre salle de classe</h3><div className="environment-story"><p>Pendant la récréation, le directeur annonce un concours de la plus belle salle de classe. Dès l’après-midi, la maîtresse propose de décorer et de nettoyer la classe. Les élèves partagent les tâches : Miara et son amie fabriquent des guirlandes et des mobiles ; Youssef et Linda couvrent le bureau ; Aden ramasse les papiers ; Alaa apporte des plantes ; Emma et Amir dessinent des paysages et les collent sur les murs.</p><p>Peu à peu, la salle se transforme : les murs sont colorés, les tables rangées et le sol propre. Les élèves admirent leur travail avec fierté. La classe est propre, lumineuse et accueillante.</p></div><h3>Situation 2 : Un geste pour notre quartier</h3><div className="environment-story"><p>Dimanche matin, les habitants se réunissent pour la journée de la propreté. Des sacs en plastique volent et des ordures salissent le sol. Les équipes ramassent les bouteilles et les cartons, nettoient les murs et plantent des fleurs le long des trottoirs. Elles arrosent aussi les jeunes arbres. En fin d’après-midi, le quartier est propre, parfumé et accueillant. Les habitants comprennent qu’un effort collectif peut transformer leur espace de vie.</p></div><h3>Mots-clés · كلمات أساسية</h3><p><strong>embellir</strong> = يُجمّل · <strong>nettoyer</strong> = ينظّف · <strong>une guirlande</strong> = زينة معلّقة · <strong>un mobile</strong> = معلّقة متحرّكة · <strong>une poubelle</strong> = سلّة المهملات · <strong>planter</strong> = يزرع · <strong>arroser</strong> = يسقي · <strong>un trottoir</strong> = رصيف · <strong>un effort collectif</strong> = جهد جماعي · <strong>accueillant</strong> = مرحّب / مريح.</p><Answer label="Questions : que font les habitants ? Quand terminent-ils ? Quelles sont les trois actions principales ?" lines={3} /><Correction>Ils organisent une journée de propreté. Ils terminent en fin d’après-midi. Les trois actions sont ramasser les déchets, nettoyer les murs et planter des fleurs. « Propre » a pour synonyme « net » ou « accueillant » dans le texte ; l’antonyme de « joyeux » est « triste ». « Change complètement de visage » signifie change totalement d’aspect. Ils travaillent ensemble : « Les parents et les enfants s’organisent en petites équipes. » Le quartier était sale : « Des sacs en plastique volent et des ordures salissent le sol. » Ils sont satisfaits : « Fatigués mais fiers ». Sans entretien, les déchets reviendront et le quartier deviendra sale et pollué.</Correction></section>

    <section className="environment-section"><h2>Conjugaison · passé composé, présent et futur</h2><p><strong>Passé :</strong> hier, l’année dernière. <strong>Présent :</strong> aujourd’hui, maintenant, en ce moment. <strong>Futur :</strong> demain, l’année prochaine.</p><p><strong>Passé composé</strong> : Hier, j’ai joué. · <strong>Présent</strong> : Maintenant, je joue. · <strong>Futur</strong> : Demain, je jouerai.</p><Answer label="Ex. 1 : relie demain, hier, en ce moment, l’année dernière, aujourd’hui au passé, présent ou futur." /><Answer label="Ex. 2-3 : indique le temps : Aujourd’hui, nous jouons. Hier, j’ai regardé. Demain, la maîtresse parlera. Maintenant, tu es sérieux. La semaine dernière, ils ont visité Tunis." lines={3} /><Answer label="Ex. 4 : choisis la bonne forme dans les dix phrases avec hier, maintenant, demain, en ce moment, aujourd’hui et l’année prochaine." lines={4} /><Correction>Hier et l’année dernière indiquent le passé ; en ce moment et aujourd’hui indiquent le présent ; demain et l’année prochaine indiquent le futur. Les réponses de l’exercice 4 sont : a lavé, écoutent, mangeras, décorons, avez visité, brille, entrerons, as allumé, parle, habiteront.</Correction><h3>Vocabulaire · المفردات</h3><p><strong>agréable</strong> : جميل / لطيف · <strong>propre</strong> : نظيف · <strong>sale</strong> : متّسخ · <strong>spacieux</strong> : واسع · <strong>décorer</strong> : يزيّن · <strong>suspendu</strong> : معلّق · <strong>vert</strong> : أخضر · <strong>fleuri</strong> : مزهر · <strong>tranquille</strong> : هادئ · <strong>sain</strong> : سليم / صحي · <strong>lumineux</strong> : مضيء · <strong>ordonné</strong> : مرتّب.</p></section>

    <section className="environment-section"><h2>De l’oral à l’écrit</h2><p>Lis les situations suivantes puis raconte une action utile pour l’environnement.</p><div className="ending-grid"><span><strong>Le reboisement</strong><br />Accrocher des nichoirs et protéger les oiseaux.</span><span><strong>Le nettoyage</strong><br />Balayer, ramasser les feuilles et mettre les déchets dans un sac.</span><span><strong>Le tri sélectif</strong><br />Trier le plastique, le papier, le verre et le métal.</span><span><strong>La fête de l’arbre</strong><br />Creuser, planter de jeunes arbustes et les arroser.</span><span><strong>Le potager</strong><br />Cultiver des légumes frais dans des bacs.</span><span><strong>Les façades vertes</strong><br />Arroser les plantes et purifier l’air.</span></div><h3>Une chambre propre et agréable</h3><p>Alain et Aline rangent une chambre en désordre. Alain ouvre la fenêtre et range les objets ; Aline plie les vêtements et les met dans l’armoire. Ensuite, ils font les lits et essuient la poussière. Après une heure, la chambre est propre et ordonnée.</p><Answer label="Production : explique comment rendre ton école ou ton quartier plus agréable." lines={7} /><Correction>Exemple : Nous organisons une journée de nettoyage dans la cour. Nous ramassons les papiers et nous les mettons dans la poubelle. Ensuite, nous plantons des fleurs et nous arrosons les arbres. Nous trions le plastique et le papier. Il ne faut pas écrire sur les murs. Grâce à nos efforts, notre école devient propre, lumineuse et agréable.</Correction></section>

    <section className="environment-section"><h2>Module 2 · Apprenons à vivre ensemble</h2><h3>Texte 1 : Une amitié sous la pluie</h3><div className="environment-story"><p>Après la pluie, Mayar sort à bicyclette. Elle éclabousse sans le vouloir Adam, qui se fâche. Mayar s’arrête, s’excuse et lui prête son vélo pour rentrer se changer. Le lendemain, Adam rend le vélo. Les enfants discutent, rient et découvrent qu’ils habitent près l’un de l’autre. Une belle amitié naît entre eux.</p></div><h3>Texte 2 : Les deux voisines</h3><div className="environment-story"><p>Madame Martin voit des déchets devant sa maison et se met en colère contre Madame Duval. Celle-ci explique qu’elle n’a pas trouvé la grande poubelle, puis elle nettoie la place. Les deux voisines discutent calmement et comprennent qu’un malentendu a causé la dispute. Elles se réconcilient et décident de mieux se respecter et de s’entraider.</p></div><h3>Mots-clés · كلمات أساسية</h3><p><strong>éclabousser</strong> = يرشّ بالماء · <strong>s’excuser</strong> = يعتذر · <strong>pardonner</strong> = يسامح · <strong>un malentendu</strong> = سوء تفاهم · <strong>se réconcilier</strong> = يتصالح · <strong>s’entraider</strong> = يتعاون · <strong>la solidarité</strong> = التضامن · <strong>le respect</strong> = الاحترام · <strong>la tolérance</strong> = التسامح · <strong>la coopération</strong> = التعاون.</p><Correction>Mayar et Adam deviennent amis parce qu’elle s’excuse et lui prête son vélo. Les voisines se réconcilient après avoir parlé calmement et nettoyé la place. Le message des deux textes est qu’il faut respecter les autres, s’excuser, pardonner et coopérer.</Correction></section>

    <section className="environment-section"><h2>Grammaire · phrases affirmatives et négatives</h2><p>La phrase négative encadre le verbe avec <strong>ne… pas</strong>, <strong>ne… plus</strong> ou <strong>ne… jamais</strong>.</p><Answer label="Ex. 1 : mets à la forme négative : Mayar a fait exprès. Les voisines se disputent souvent. Le vent a soufflé fort." lines={3} /><Answer label="Ex. 2 : mets à la forme affirmative : Madame Duval n’a pas trouvé la poubelle. Les enfants ne se sont pas fâchés. La pluie ne tombe plus." lines={3} /><Answer label="Ex. 3-4 : complète avec ne… pas, ne… plus ou ne… jamais, puis transforme les trois phrases." lines={4} /><Correction>Exemples : Mayar n’a pas fait exprès. Les voisines ne se disputent pas souvent. Le vent n’a pas soufflé fort. Madame Duval a trouvé la poubelle. Les enfants se sont fâchés. La pluie tombe encore. Adam ne veut plus sortir sous la pluie. Ils ne se disputent jamais. Nous ne laisserons jamais nos voisins sans aide. Je n’ai plus d’argent. Le garçon n’est pas content. Elle ne comprend jamais la leçon.</Correction></section>

    <section className="environment-section"><h2>Conjugaison, orthographe et valeurs</h2><p><strong>Être au présent :</strong> je suis, tu es, il est, nous sommes, vous êtes, ils sont. <strong>Au futur :</strong> je serai, tu seras, il sera, nous serons, vous serez, ils seront. <strong>Avoir :</strong> j’ai, tu as, il a, nous avons, vous avez, ils ont ; futur : j’aurai, tu auras, il aura, nous aurons, vous aurez, ils auront.</p><Answer label="Conjugue être ou avoir : Les voisines ___ des amies. Je ___ content. Tu ___ gentil. Nous ___ un bon voisinage. Les enfants ___ froid. J’___ une idée." /><Answer label="Mets au futur : Nous sommes unis. Je suis solidaire. Les voisines ont une bonne relation. Tu as le temps de m’écouter." lines={3} /><p><strong>Le son g :</strong> g devant a, o, u donne [gue] : gâteau, gomme, goût. Pour garder [gue] devant e ou i, on écrit gu : guitare, guide.</p><Answer label="Complète avec g ou gu : une ___itare, une ___omme, des ___enoux, un ___âteau. Barre l’intrus : gilet, généreux, gigot, gomme." lines={3} /><Correction>Être : sont, suis, es. Avoir : avons, ont, ai. Au futur : Nous serons unis. Je serai solidaire. Les voisines auront une bonne relation. Tu auras le temps de m’écouter. Orthographe : guitare, gomme, genoux, gâteau. Dans « gilet, généreux, gigot, gomme », gomme est l’intrus car g se prononce [gue] ; les autres donnent [j].</Correction><h3>Valeurs humaines · القيم الإنسانية</h3><p><strong>amitié</strong> صداقة · <strong>paix</strong> سلام · <strong>égalité</strong> مساواة · <strong>bonté</strong> طيبة · <strong>partage</strong> مشاركة · <strong>écoute</strong> إنصات · <strong>pardon</strong> مسامحة · <strong>gentillesse</strong> لطف · <strong>généreux</strong> كريم · <strong>tolérant</strong> متسامح · <strong>solidaire</strong> متضامن. À retenir : « L’union fait la force. » = الاتحاد قوة.</p></section>

    <section className="environment-section"><h2>Production écrite</h2><p>Raconte une situation où des personnes apprennent à vivre ensemble. Utilise des connecteurs, une phrase affirmative et une phrase négative.</p><Answer label="Ma production" lines={9} /><Correction>Exemple : Un jour, deux voisins se disputent à cause des déchets. L’un d’eux explique calmement le problème. L’autre s’excuse et nettoie la rue. Ils ne veulent plus se disputer. Ils décident de respecter les règles et de s’entraider. Finalement, leur quartier devient plus propre et plus paisible. Grâce au dialogue, ils retrouvent l’amitié et la confiance.</Correction></section>
    <Link className="environment-quiz-link" to="/courses/5eme/francais/modules-1-2/quiz">🎯 Ouvrir le quiz /20 →</Link>
  </div>
}

export default FrenchFifthModules