import { Link } from 'react-router-dom'
import './ModuleSix.css'

function Answer({ label, lines = 1 }) { return lines > 1 ? <label className="present-answer">{label}<textarea rows={lines} /></label> : <label className="present-answer">{label}<input type="text" /></label> }
function Correction({ children }) { return <details className="correction"><summary>Voir la correction</summary><p>{children}</p></details> }
function Section({ title, children, correction }) { return <section className="lesson-section"><h2>{title}</h2>{children}<details className="correction"><summary>Voir la correction</summary><p>{correction}</p></details></section> }

function FrenchSixthAcceptance() {
  return <div className="module-page"><div className="module-heading"><p className="eyebrow">Français · 6e année</p><h1>Module 3 : Accepter les autres</h1><p>Respect, tolérance, solidarité, adjectifs, être et avoir, homophones et production écrite.</p><Link className="button-link" to="/courses/6eme/francais/accepter-les-autres/quiz">Ouvrir le quiz /20 →</Link></div>
    <Section title="1. Comprendre le thème" correction="Il faut accepter autrui avec ses différences et soi-même avec ses qualités et ses défauts. Les différences peuvent être physiques, culturelles ou liées aux opinions. On accepte les autres à l’école, à la maison et partout, tous les jours, en étant gentil, tolérant, respectueux et solidaire. Il ne faut pas être raciste, égoïste ou agressif, ni se moquer des autres."><p><strong>Accepter qui ?</strong> Les autres avec leurs différences et soi-même avec ses qualités et ses défauts.</p><p><strong>Quelles différences ?</strong> Physiques : couleur de peau, taille, yeux, cheveux. Culturelles : pays, langue, traditions. Opinions : être d’accord ou ne pas être d’accord.</p><p><strong>Comment accepter ?</strong> Être souriant, gentil, tolérant, respectueux et aimable ; tendre la main, aider et défendre les autres ; ne pas mépriser, insulter ou rejeter.</p><h3>À retenir</h3><p>Nous sommes tous différents mais semblables. Chaque personne est digne de respect. La diversité est une richesse et l’union fait la force.</p><h3>Vocabulaire thématique</h3><div className="job-grid"><span>accepter ≠ refuser / rejeter</span><span>aider · aimer · respecter</span><span>les personnes âgées · les pauvres · les orphelins</span><span>les différences · le tort · l’erreur</span><span>gentil, généreux, poli, solidaire</span><span>méchant, raciste, égoïste, cruel</span><span>le pardon · la paix · la tolérance</span><span>se moquer · taquiner · vexer · malmener</span></div><p><strong>Respecter</strong> : honorer, tolérer. Contraires : mépriser, ridiculiser, insulter, humilier. <strong>Respectueux</strong> : humble, attentif, attaché. Contraires : impoli, insolent, méprisant.</p></Section>

    <Section title="2. Grammaire : adjectifs épithètes et attributs" correction="Ex. 1 : actif (a), nouveaux (e), immobile (a), meilleure (e), fatigué (a), magnifiques (a). Ex. 2 : ce grand garçon ; une nouvelle blouse blanche ; les pompiers courageux ; cette hôtesse gentille ; ce bel enfant. Ex. 3 : des yeux sont châtains ; l’hôpital est grand ; les comprimés sont amers. Ex. 4 : curieuse, meublées, intelligente, silencieux, stagiaires, neuve."><p>L’adjectif <strong>épithète</strong> est placé près du nom : <em>une meilleure amie</em>. L’adjectif <strong>attribut</strong> est relié au sujet par un verbe d’état : <em>la voisine est curieuse</em>.</p><Answer label="Ex. 1 : indique e ou a pour les adjectifs de six phrases." lines={3} /><Answer label="Ex. 2-3 : enrichis les groupes nominaux puis transforme les épithètes en attributs." lines={4} /><Answer label="Ex. 4 : complète avec silencieux, neuf, meublé, stagiaire, curieux ou intelligent." /></Section>

    <Section title="3. Conjugaison : être et avoir" correction="Ex. 1 : ont eu (passé composé), serai (futur), aurez (futur), es (présent), avons été (passé composé), ont (présent), ai été (passé composé), a eu (passé composé), sommes (présent). Ex. 2 : Grand-mère aura mal aux dents. Tu seras surpris. Je n’aurai pas de chance. Vous serez fiers. Nous aurons besoin d’eau. Elles seront gaies. Ex. 3 : Le secouriste a été courageux. Elle a été joyeuse. On n’a pas eu peur. Tu n’as pas été absent. Nous avons été en 5e année. J’ai été en vacances. Ils ont eu froid. Vous avez été courageux."><p><strong>Présent :</strong> je suis / j’ai, tu es / tu as, il est / il a, nous sommes / avons, vous êtes / avez, ils sont / ont.</p><p><strong>Passé composé :</strong> j’ai été, j’ai eu. <strong>Futur :</strong> je serai, j’aurai.</p><Answer label="Ex. 1 : souligne le verbe et indique son temps dans les neuf phrases." lines={4} /><Answer label="Ex. 2 : transforme au futur. Ex. 3 : transforme au passé composé." lines={5} /></Section>

    <Section title="4. Orthographe : son / sont" correction="Les réponses sont : sont, son, sont, sont, son, son. Phrases : Amel et son père sont allés. Moncef, son père et son frère sont de bons chasseurs. Zina emmène son grand-père. Latifa et son frère sont invités. Les infirmières sont très gentilles. Omar aide toujours son voisin handicapé. Les enfants sont allés rendre visite à leurs grands-parents. Phrases remises en ordre : Alain et son ami sont partis seuls en vacances. La mère et son fils sont au dispensaire. Le père et son fils sont convoqués chez le directeur."><p>On écrit <strong>sont</strong> si on peut remplacer par <em>étaient</em>. On écrit <strong>son</strong> devant un nom si on peut remplacer par <em>mon</em> ou <em>ton</em>.</p><Answer label="Complète par son ou sont dans le texte sur Mme Drouot et les enfants." lines={3} /><Answer label="Remets en ordre : son - ami - partis - Alain - sont - et - seuls - en vacances." /><Answer label="Remets en ordre les deux phrases suivantes sur la mère, le père et le fils." /><Correction>Astuce : « Les infirmières sont gentilles » → « Les infirmières étaient gentilles ». « son voisin » → « mon voisin ».</Correction></Section>

    <Section title="5. Outils pour la production écrite" correction="Choisis un verbe qui correspond au sens et conjugue-le correctement : demander/interroger pour une question ; répondre/affirmer pour une information ; protester/s’indigner pour s’opposer ; expliquer/préciser pour donner une explication ; ordonner/exiger pour un ordre ; supplier pour une prière ; hésiter/bégayer pour une hésitation ; s’étonner/s’inquiéter pour une surprise ; crier/hurler pour une voix forte ; chuchoter/murmurer pour une voix basse."><p>Les verbes introducteurs rendent un dialogue vivant : <em>demande-t-elle, répond-il, s’écrie-t-elle, explique-t-il, murmure-t-il, proteste-t-elle</em>.</p><Answer label="Complète : Pour interroger, je peux écrire ___. Pour répondre, ___. Pour crier, ___. Pour parler à voix basse, ___." lines={2} /></Section>

    <Section title="6. Productions écrites modèles" correction="Un bon récit présente les personnages, la situation, le problème, les dialogues et la solution. Il montre le respect, la solidarité et l’acceptation des différences."><h3>L’enfant handicapé</h3><p>Mario ne peut plus marcher après un accident. Ses amis l’emmènent à la campagne et l’aident à profiter de la promenade. Il les remercie et ils lui répondent que c’est leur devoir.</p><h3>Violetta et la solidarité</h3><p>Violetta est rejetée par des camarades à cause de ses vêtements. Une élève intervient, condamne les moqueries et encourage les filles à s’excuser. Elles reconnaissent leur tort, aident Violetta et apprennent que la solidarité rend heureux.</p><h3>Sujet : un nouvel élève différent</h3><Answer label="Raconte l’arrivée de Sami, ses difficultés de prononciation, les moqueries, le dialogue et la solution." lines={9} /><h3>Sujet : un vieillard non-voyant</h3><Answer label="Raconte comment tu aides un vieillard non-voyant à traverser la rue et rapporte le dialogue." lines={9} /><Correction>Utilise : « Arrêtez ! », crie la maîtresse. « Il faut respecter nos camarades », explique-t-elle. « Merci, tu m’as sauvé la vie », répond le vieil homme. Termine par une solution positive : Sami devient l’ami de tous ; le vieillard arrive en sécurité.</Correction></Section>
    <Link className="button-link" to="/courses/6eme/francais/accepter-les-autres/quiz">Ouvrir le quiz /20 →</Link>
  </div>
}

export default FrenchSixthAcceptance