import { Link } from 'react-router-dom'
import './FrenchPresent.css'

function Answer({ label, lines = 1 }) {
  return lines > 1 ? <label className="present-answer">{label}<textarea rows={lines} /></label> : <label className="present-answer">{label}<input type="text" /></label>
}

function Correction({ children }) {
  return <details className="present-correction"><summary>Voir la correction</summary>{children}</details>
}

function FrenchSeventhControl() {
  return <div className="present-page"><header className="present-heading"><p className="eyebrow">Français · 7e année de base</p><h1>Devoir de contrôle n°1</h1><p>Français · Mme M’Ghirbi · École Prep. Med Bachrouche 7 · Durée : 1 heure · Coefficient : 1</p><Link className="present-quiz-link" to="/courses/7eme/francais/devoir-controle-1/quiz">Ouvrir l’évaluation interactive /20 →</Link></header>
    <section className="present-section"><h2>Texte : La mère et l’enfant</h2><div className="present-reading"><p>Maman, tu es toute petite, tu portes un bonnet blanc, un corsage noir et un tablier bleu. Tu marches dans notre maison, tu ranges le ménage, tu fais la cuisine et tu es maman. Tu te lèves le matin pour balayer, puis tu prépares la soupe, et puis tu viens m’éveiller. J’entends tes pas sur les marches de l’escalier. C’est le jour qui arrive avec l’école, et je ne suis pas bien content. Mais tu ouvres la porte, c’est maman qui vient avec du courage et de la bonté. Tu m’embrasses, et je passe les bras autour de ton cou et je t’embrasse… Tu es une bonne divinité qui chasse la paresse. Tu entrouvres la fenêtre, et l’air et le soleil, c’est toi… Tu es à la source de mes actions, tes gestes me donnent mes premières pensées et ta tendresse me donne mon premier bonheur.</p><p>Maman, tu es travailleuse. Le travail de mon père est celui qui nous donne la vie et ton travail consiste à l’ordonner. Le bruit de ta besogne est le bruit du temps qui passe chaque jour avec des repas, du travail et du repos. Tu veux que rien ne manque : ton corps, tes mains, tes yeux et tes jambes s’occupent de ce soin et je sens que tu en as fait les serviteurs de notre vie et les ordonnateurs de notre joie.</p><p>Il y a la vaisselle, le ménage, la cuisine, le puits plein d’eau que tu puises, le balai et la lessive. Il y a les commissions chez l’épicier, chez le boucher et chez tous les marchands. Il y a le raccommodage et la confection. Ce sont des travaux simples que tu accomplis sans cesse.</p></div><p><strong>Charles-Louis Philippe, La mère et l’enfant.</strong></p><p><em>Une divinité : un dieu. Une besogne : un travail. Le raccommodage : l’action de réparer un vêtement.</em></p></section>
    <section className="present-section"><h2>I. Compréhension · /10</h2><Answer label="1. De qui le narrateur parle-t-il ?" lines={2} /><Answer label="2. Quelles tâches la maman fait-elle chaque jour ?" lines={2} /><Answer label="3. Qu’a appris l’enfant en regardant sa mère ?" lines={2} /><Answer label="4. Quel rôle important la mère joue-t-elle dans sa famille ?" lines={2} /><Answer label="5. Quels sentiments l’enfant éprouve-t-il pour sa maman ?" lines={2} /><Correction><p>1. Le narrateur parle de sa maman. 2. Elle fait la vaisselle, le ménage, la cuisine, la lessive, les courses, le raccommodage et la confection. 3. Il a appris le courage, le travail, la patience et la responsabilité. 4. Elle organise la vie de la famille et veille à ce que rien ne manque. 5. Il éprouve pour elle de l’amour, de la tendresse, de l’admiration et de la reconnaissance.</p></Correction></section>
    <section className="present-section"><h2>II. Langue · /10</h2><h3>Vocabulaire</h3><Answer label="1. Élimine l’intrus : famille · sœur · couvert · maternel · fils." /><Answer label="2. Conjugue voir ou regarder : L’enfant ___ sa maman en train de laver la vaisselle. Chaque matin, il ___ sa mère entrer dans sa chambre." /><h3>Grammaire</h3><Answer label="3. Pose les questions correspondant aux réponses : « Le travail du père leur donne la vie. » / « Sa mère est travailleuse. »" lines={2} /><Answer label="4. Transforme à l’impératif : « Tu regardes le suivant et tu pars où il te conduit. »" /><Answer label="5. Produis une phrase exclamative affirmative à propos de la mère." /><h3>Conjugaison et orthographe</h3><Answer label="6. Mets au passé composé ou au présent : Hier, le boulanger (se dépêcher) ___. Les campeurs (préférer) ___ découvrir le lieu tout de suite. Le policier (interdire) ___, avant-hier, au piéton de traverser." lines={2} /><Answer label="7. Complète par ce/se, ces/ses, c’est/s’est : ___ avec l’ordinateur que Thomas corrige ___ fautes. J’ai trouvé des romans de Jules Verne ; j’ai lu ___ livres avec plaisir." lines={2} /><Correction><p>1. « couvert » est l’intrus : les autres mots appartiennent à la famille ou la caractérisent. 2. L’enfant regarde sa maman. Chaque matin, il voit sa mère entrer dans sa chambre. 3. Quel travail leur donne la vie ? Comment est sa mère ? 4. Regarde le suivant et pars où il te conduit ! 5. Quelle maman courageuse ! 6. Hier, le boulanger s’est dépêché. Les campeurs préfèrent découvrir le lieu tout de suite. Le policier a interdit au piéton de traverser. 7. C’est avec l’ordinateur que Thomas corrige ses fautes. J’ai trouvé des romans de Jules Verne ; j’ai lu ces livres avec plaisir.</p></Correction></section>
    <section className="present-section"><h2>Barème et relecture</h2><p>Compréhension : 10 points. Langue : 10 points. Relis les accords, les temps verbaux, les homophones et la ponctuation avant de rendre ton devoir.</p></section>
  </div>
}

export default FrenchSeventhControl