import { Link } from 'react-router-dom'
import './FrenchFifth.css'

function Answer({ label, lines = 1 }) { return lines > 1 ? <label className="environment-answer">{label}<textarea rows={lines} /></label> : <label className="environment-answer">{label}<input type="text" /></label> }
function Correction({ children }) { return <details className="environment-correction"><summary>✅ Voir la correction</summary><p>{children}</p></details> }

function FrenchFifthEnvironment() {
  return (
    <div className="environment-page">
      <header className="environment-heading"><p className="eyebrow">Français · 5th form</p><h1>🌿 Une idée géniale</h1><p>Lecture, vocabulaire, grammaire, conjugaison et orthographe autour de l’environnement.</p><Link className="environment-quiz-link" to="/courses/5eme/francais/environnement/quiz">🎯 Ouvrir le quiz séparé /20 →</Link></header>

      <section className="environment-section"><h2>📖 Lecture : Une idée géniale</h2><div className="environment-story"><p>La famille Driss vient d’emménager à la campagne. Un jour, après le déjeuner, la maman explique qu’elle reste seule presque toute la journée et qu’elle s’ennuie. Le père propose de rendre visite aux voisins, de faire des courses ou de tricoter, mais la maman refuse.</p><p>Soudain, Mireille s’écrie : « J’ai une idée ! » Elle propose d’élever des animaux domestiques : des poules, des chèvres et des moutons. Le père trouve que c’est une bonne proposition. La mère embrasse sa fille et dit : « C’est une idée géniale. »</p></div><h3>Je comprends les mots</h3><p><strong>Une proposition</strong> = une idée, un projet. <strong>Se propage</strong> = se répand, se diffuse. <strong>Monotone</strong> = qui est toujours pareil. <strong>Élever</strong> = s’occuper d’animaux pour les faire grandir.</p><h3>Questions</h3><Answer label="1. Le père a-t-il un problème à discuter ? Vrai ou faux ? 2. Le père trouve-t-il une solution ? Vrai ou faux ? 3. La fille propose-t-elle une bonne solution ? Vrai ou faux ?" lines={3} /><Answer label="4. La mère refuse-t-elle la proposition de sa fille ? Oui ou non ? Relève la phrase du texte." lines={3} /><Answer label="5. Une idée géniale signifie : une mauvaise idée / une bonne idée / une idée stupide. 6. Trouve une autre occupation pour la maman." lines={3} /><Correction>1. Faux : c’est la maman qui a un problème. 2. Faux : c’est Mireille qui propose la solution. 3. Vrai. 4. Non. Elle dit : « C’est une idée géniale. » 5. Une idée géniale est une bonne idée. 6. Exemple : elle peut jardiner, lire ou faire de la peinture.</Correction></section>

      <section className="environment-section"><h2>🌱 1. Vocabulaire : le jardin et la classe</h2><p>Classe les mots : un arrosoir, des gravures, un tableau d’affichage, un tuyau, des rideaux, une pelle, des pots de fleurs, embellir, accrocher, désherber.</p><Answer label="Jardin : ___  Classe : ___" lines={3} /><Correction>Jardin : un arrosoir, un tuyau, une pelle, des pots de fleurs, désherber. Classe : des gravures, un tableau d’affichage, des rideaux, accrocher. <strong>Embellir</strong> peut s’utiliser pour le jardin ou la classe.</Correction><h3>Protéger la nature</h3><Answer label="Écris une action à faire et une action à ne pas faire pour protéger la nature." lines={3} /><Correction>À faire : arroser les plantes, expliquer pourquoi il faut protéger la nature. À ne pas faire : cueillir inutilement les fleurs ou toucher les nids et les œufs.</Correction><h3>Complète</h3><Answer label="Le jardinier utilise un ___ pour arroser. Il faut ___ le jardin. Nous allons ___ des rideaux. Les pots de fleurs peuvent ___ le balcon." /><Correction>arrosoir · désherber · accrocher · embellir.</Correction></section>

      <section className="environment-section"><h2>❓ 2. Grammaire : les types de phrases</h2><p><strong>Déclarative</strong> : elle dit quelque chose et se termine par un point. <strong>Interrogative</strong> : elle pose une question et se termine par ?. <strong>Exclamative</strong> : elle exprime une émotion et se termine par !</p><Answer label="Indique le type : Il faut protéger notre environnement. / Est-ce que tu as arrosé les plantes ? / Quel beau jardin ! / Les enfants nettoient la cour. / Ne jette pas ces papiers !" lines={3} /><Answer label="Ajoute . ? ou ! : Range tes affaires dans la classe ___ Quelle belle idée ___ Pourquoi ne dois-je pas cueillir les fleurs ___ Nous devons planter des arbres ___" lines={3} /><Answer label="Transforme : Les élèves embellissent la classe. → question : ___ → exclamation : ___" lines={3} /><Correction>Déclarative, interrogative, exclamative, déclarative, exclamative. Ponctuation : ! · ! · ? · . Exemple : Est-ce que les élèves embellissent la classe ? / Comme les élèves embellissent bien la classe !</Correction></section>

      <section className="environment-section"><h2>⏰ 3. Conjugaison : les indicateurs de temps</h2><p>Passé : hier, avant-hier, la semaine dernière. Présent : maintenant, aujourd’hui, en ce moment, chaque jour. Futur : demain, après-demain, la semaine prochaine, l’année prochaine.</p><Answer label="Choisis : Hier, nous (avons planté / plantons / planterons). Demain, les élèves (ont nettoyé / nettoient / nettoieront). En ce moment, le jardinier (a arrosé / arrose / arrosera). L’année prochaine, nous (avons créé / créons / créerons)." lines={3} /><Answer label="Conjugue : Chaque jour, elle (arroser) ___. La semaine dernière, ils (ramasser) ___. Après-demain, nous (embellir) ___." /><Answer label="Écris une phrase au présent, une au passé et une au futur sur l’environnement." lines={4} /><Correction>Hier, nous avons planté. Demain, les élèves nettoieront. En ce moment, le jardinier arrose. L’année prochaine, nous créerons. Elle arrose · ils ont ramassé · nous embellirons. Exemple : Aujourd’hui je plante. Hier j’ai nettoyé. Demain je protégerai la nature.</Correction></section>

      <section className="environment-section"><h2>🔤 4. Orthographe : le son [é]</h2><p>Le son [é] peut s’écrire <strong>é</strong> : café, <strong>er</strong> : oranger, <strong>et</strong> : robinet, <strong>ez</strong> : chez, <strong>es</strong> : mes.</p><Answer label="Complète : Le jardini___ arrose. Nous devons prot___ la nature. Le bouqu___ sent bon. Ch___ nous, il y a un jardin. Les l___ sont rangés." /><Answer label="Classe : café, désherber, carnet, chez, mes, planter, nez, clé, arroser." lines={3} /><Answer label="Écris une phrase avec deux mots qui se terminent par le son [é]." lines={3} /><Correction>jardinier · protéger · bouquet · chez · livres. Classe : é = café, clé · er = désherber, planter, arroser · et = carnet · ez = chez, nez · es = mes. Exemple : Chez le jardinier, j’ai acheté une clé.</Correction></section>

      <section className="environment-section"><h2>✍️ 5. Production écrite</h2><p>Écris 6 à 8 phrases pour expliquer comment rendre ton école ou ton quartier plus agréable.</p><Answer label="Ma production" lines={8} /><Correction>Exemple : Nous devons protéger la cour de l’école. Nous pouvons planter des arbres et arroser les fleurs. Il ne faut pas jeter les papiers par terre. Les élèves peuvent désherber le jardin. Nous devons respecter les oiseaux et leurs nids. Ainsi, notre environnement devient plus agréable.</Correction></section>
      <Link className="environment-quiz-link" to="/courses/5eme/francais/environnement/quiz">🎯 Ouvrir le quiz séparé /20 →</Link>
    </div>
  )
}

export default FrenchFifthEnvironment
